---
- hosts: all
  gather_facts: no

  tasks:
  - name: install ntpd
    yum:
      name: ntp
      state: latest
      
  - name: enable and start ntpd
    service:
      name: ntpd
      state: started
      enabled: yes

