- name: Install Tower plugin into Jenkins
  hosts: all
  
  tasks:
  - name: Invoke Jenkins plugin Module
    jenkins_plugin:
      name: "{{ item }}"
      state: latest
      url_username: admin
      url_password: admin
      url: http://localhost:8080
      with_dependencies: yes
    with_items:
      - ansible-tower
      - credentials
      - script-security
      - structs
      
      
  - name: Restart Jenkins
    service: 
      name: jenkins
      state: restarted
