- name: Install Tower plugin into Jenkins
  hosts: all
  
  tasks:
  - name: Invote Jenkins plugin Module
    jenkins_plugin:
      name: ansible-tower
      state: latest
      url_username: admin
      url_password: admin
      url: http://localhost:8080
      
  - name: Restart Jenkins
    service: 
      name: jenkins
      state: restarted
