---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Create an incident
    snow_record:
      username: admin
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      data:
        short_description: "This is a test incident opened by Ansible"
        severity: 3
        priority: 2
    register: new_incident
    
  - name: Show incident just created
    debug:
      msg: "{{ new_incident }}"

  - name: Delete the record we just made
    snow_record:
      username: admin
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      number: "{{new_incident['record']['number']}}"
