---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Create an incident
    snow_record:
      username: admin
      password: "{{ snow_password }}"
      instance: dev59643
      state: present
      data:
        short_description: "This is a test incident opened by Ansible"
        severity: 3
        priority: 2
    register: new_incident
